
export enum Diet {
  None = 'Keine Einschränkung',
  Vegetarian = 'Vegetarisch',
  Vegan = 'Vegan',
  Pescetarian = 'Pescetarisch',
  GlutenFree = 'Glutenfrei',
  LactoseFree = 'Laktosefrei',
  Halal = 'Halal',
  NoPork = 'Kein Schweinefleisch'
}

export enum Goal {
  Maintain = 'Gewicht halten',
  Lose = 'Abnehmen',
  BuildMuscle = 'Muskelaufbau'
}

export enum MealType {
  Breakfast = 'Frühstück',
  Lunch = 'Mittagessen',
  Dinner = 'Abendessen',
  Leftovers = 'Reste'
}

export interface AppSettings {
  preferredStore: string;
  theme: 'light' | 'dark';
  useThermomix: boolean;
  useLeftovers: boolean;
  weekStartDay: string; // e.g. 'Montag'
  includeWeekends: boolean;
}

export interface UserProfile {
  id: string;
  name: string;
  diet: Diet;
  calories: number;
  goal: Goal;
  allergies: string; // Comma separated
  dislikes: string; // Comma separated
  favoriteCuisine?: string; // e.g. "Italienisch", "Asiatisch"
  budget: number; // Weekly budget
  homeTimes: {
    [key: string]: boolean; // e.g., "Montag_Frühstück": true
  };
}

export interface Ingredient {
  name: string;
  amount: number;
  unit: string;
}

export interface Recipe {
  id: string; // Generated by AI or frontend
  name: string;
  ingredients: Ingredient[];
  instructions: string[];
  calories: number;
  cookingTime: number; // in minutes
  tags: string[];
  rating?: number; // 1-5
  isFavorite?: boolean;
  source?: 'ai' | 'manual';
}

export interface MealSlot {
  type: MealType;
  recipe: Recipe;
  eaters: string[]; // List of user IDs eating this
  completed?: boolean;
  isLeftover?: boolean; // Marks a Reste meal — recipe is shared with previous day's dinner
}

export interface DayPlan {
  day: string; // Montag, Dienstag, etc.
  meals: MealSlot[];
}

export interface WeeklyPlan {
  weekId: string;
  startDate: string; // ISO Date string YYYY-MM-DD representing the Monday of the week
  days: DayPlan[];
  generatedAt: string;
}

export interface ShoppingItem {
  name: string;
  amount: number;
  unit: string;
  category: string;
  checked: boolean;
}

export interface ShoppingList {
  items: ShoppingItem[];
  estimatedTotal: number;
}

// Helper type for generation
export interface GenerationRequestProfile {
    user: UserProfile;
    activeTimes: { [key: string]: boolean };
}

export interface RecipePreferences {
  favorites: string[]; // List of recipe names
  highlyRated: string[]; // List of recipe names (4-5 stars)
  disliked: string[]; // List of recipe names (1-2 stars)
  customRecipes: Recipe[]; // Full objects of custom recipes
}